name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Specify your .NET version

      # Change to the 'backend-module' directory where the .NET project is located
      - name: Navigate to backend-module
        run: cd backend-module

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore backend-module/sem5pi-24-25-g051.csproj

      # Build the .NET application
      - name: Build
        run: dotnet build backend-module/sem5pi-24-25-g051.csproj --no-restore --configuration Release

      # Publish the application
      - name: Publish
        run: dotnet publish backend-module/sem5pi-24-25-g051.csproj -c Release -o backend-module/publish

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image with the repository root as the context
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} -f backend-module/Dockerfile .


        
      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Run this job after the build job

    steps:
      # Set up SSH to connect to the remote server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy the Docker container on the remote server
      - name: Deploy Docker Container
        env:
          REMOTE_SERVER_IP: ${{ secrets.REMOTE_SERVER_IP }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
        run: |
          echo "REMOTE_SERVER_IP: ${REMOTE_SERVER_IP}"
          echo "REMOTE_USER: ${REMOTE_USER}"
        
          # Save the SSH private key to a file and set appropriate permissions
          echo "${SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key
    
          # SSH into the remote server and deploy
          ssh -i private_key -o StrictHostKeyChecking=no -p 11438 "${REMOTE_USER}@${REMOTE_SERVER_IP}" << EOF
            # Stop and remove the existing container if it exists
            docker rm -f myapp || true
            # Pull the latest Docker image
            docker pull ${DOCKER_IMAGE_NAME}
            # Run the Docker container on a different port if port 80 is in use
            docker run -d --name myapp -p 8080:80 ${DOCKER_IMAGE_NAME}
          EOF
          - name: Deploy Docker Container
          env:
            # REMOTE_SERVER_IP: ${{ secrets.REMOTE_SERVER_IP }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
          run: |
            echo "REMOTE_SERVER_IP: vsgate-ssh.dei.isep.ipp.pt"
            echo "REMOTE_USER: ${REMOTE_USER}"
            
            # Save the SSH private key to a file and set appropriate permissions
            echo "${SSH_PRIVATE_KEY}" > private_key
            chmod 600 private_key
        
            # SSH into the remote server and deploy
            ssh -i private_key -o StrictHostKeyChecking=no -p 11438 "${REMOTE_USER}@vsgate-ssh.dei.isep.ipp.pt" << EOF
              # Stop and remove the existing container if it exists
              docker rm -f myapp || true
              # Pull the latest Docker image
              docker pull ${DOCKER_IMAGE_NAME}
              # Run the Docker container on a different port if port 80 is in use
              docker run -d --name myapp -p 8080:80 ${DOCKER_IMAGE_NAME}
            EOF
        
      # Separate step to remove the private key
      - name: Remove private key
        run: rm private_key
        